[project]
name = "font2dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.8.5",
    "fonttools>=4.62.1",
    "numpy>=2.4.4",
    "pillow>=12.2.0",
    "pyyaml>=6.0.3",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "nbconvert>=7.17.1",
]
